"""
backend/app/main.py

FastAPI application entry point for the EmotionVision AI backend.

Run:
    python -m uvicorn app.main:app --reload --port 8000

Docs available at http://localhost:8000/docs
"""

import os

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from app.config import APP_NAME, APP_VERSION, CORS_ORIGINS, MODELS_DIR, PROJECT_ROOT
from app.routes import health, prediction, model_info

app = FastAPI(
    title=APP_NAME,
    version=APP_VERSION,
    description=(
        "Detects human faces in an uploaded image and classifies the "
        "predicted facial expression for each one. Outputs are described "
        "as *predicted facial expressions*, not a determination of a "
        "person's true internal emotional state."
    ),
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(health.router)
app.include_router(prediction.router)
app.include_router(model_info.router)

# Serves the real training charts (class_distribution.png, training_history.png,
# confusion_matrix.png) written by ml/dataset.py, ml/train.py, and
# ml/evaluate.py, so the frontend's Model page can show actual generated
# artifacts instead of placeholders. Returns a 404 for any file until it
# has actually been generated by running the training pipeline.
if os.path.isdir(MODELS_DIR):
    app.mount("/model-assets", StaticFiles(directory=MODELS_DIR), name="model_assets")




from fastapi.responses import FileResponse
import os

frontend_dist = os.path.join(PROJECT_ROOT, "frontend", "dist")
if os.path.exists(frontend_dist):
    # Mount Vite's assets directory specifically
    assets_dir = os.path.join(frontend_dist, "assets")
    if os.path.exists(assets_dir):
        app.mount("/assets", StaticFiles(directory=assets_dir), name="frontend-assets")
    
    @app.get("/{full_path:path}", tags=["frontend"], summary="Serve SPA")
    async def serve_spa(full_path: str):
        file_path = os.path.join(frontend_dist, full_path)
        if os.path.isfile(file_path):
            return FileResponse(file_path)
        return FileResponse(os.path.join(frontend_dist, "index.html"))
